export const orderUrl = 'https://www.amazon.com/Fabrique-leader-leadership-transformationnel-lint%C3%A9rieur/dp/B0GLSQF9L9/ref=sr_1_1?crid=184S01NSXIW0Q&dib=eyJ2IjoiMSJ9.mm65Y9IQLNBu_u10-jSCfQ.xzIdfglhz5VvHmHUiLrtEYtYtGkFF2NMsjWoaqsOlRQ&dib_tag=se&keywords=la+fabrique+du+leader&qid=1774279228&sprefix=la+fabrique+du+leade%2Caps%2C547&sr=8-1'

export const content = {
  fr: {
    nav: { preorder: 'Commander', excerpt: 'Télécharger un extrait', beyond: 'Au-delà du livre' },
    hero: {
      brand: 'La Fabrique du Leader',
      title: 'Forgez un leadership lucide, enraciné et profondément humain.',
      sub: 'Le guide transformationnel pour devenir un leader solide, aligné et visionnaire.',
      ctas: { preorder: 'Commander le livre', excerpt: 'Télécharger un extrait gratuit' },
    },
    audience: {
      title: 'Pour qui est ce livre ?',
      items: [
        { title: 'Jeunes professionnels', body: 'Pour clarifier sa trajectoire, construire sa discipline intérieure et poser les fondations d’un leadership solide.' },
        { title: 'Managers', body: 'Pour mieux se connaître, communiquer, déléguer, décider et renforcer une posture d’exemplarité.' },
        { title: 'Dirigeants', body: 'Pour aligner vision, décisions et action avec lucidité, caractère et cohérence intérieure.' },
        { title: 'Entrepreneurs', body: 'Pour bâtir avec vision, endurance, responsabilité et clarté dans des environnements incertains.' },
        { title: 'Responsables d’équipes', body: 'Pour accompagner, mobiliser ou orienter avec une influence plus consciente et plus juste.' },
        { title: 'RH / organisations', body: 'Pour développer une culture de leadership consciente, responsable et capable de soutenir une performance durable.' },
        { title: 'Écoles et universités', body: 'Pour accompagner étudiants et jeunes talents dans leur vision, leur agencité et leur sens des responsabilités.' },
        { title: 'Associations et groupes', body: 'Pour ouvrir des conversations collectives sur le caractère, le service, l’influence et la transformation personnelle.' },
      ],
    },
    giftGroup: {
      title: 'Offrir ou lire en groupe',
      body: 'La Fabrique du Leader se prête naturellement à la transmission. Vous pouvez l’offrir à un jeune leader, un collaborateur, un manager, un entrepreneur ou une personne en chemin de croissance. Il peut aussi servir de base à une lecture collective, une discussion d’équipe, une masterclass ou un atelier.',
      noteLabel: 'Usage collectif',
      note: 'Pour une équipe, une école, une communauté ou un club de lecture, indiquez la quantité souhaitée et le contexte : nous vous orienterons vers le format le plus adapté.',
      ctas: {
        bulk: 'Commander plusieurs exemplaires',
        team: 'Demander une offre pour mon équipe',
      },
    },
    order: {
      eyebrow: 'Commande directe',
      title: 'Commander le livre',
      intro: 'Choisissez votre offre puis poursuivez sur WhatsApp. Un message de commande sera préparé automatiquement et vous recevrez le numéro Wave pour finaliser le paiement.',
      options: [
        {
          id: 'single',
          eyebrow: 'Lecture personnelle',
          title: '1 exemplaire',
          body: 'Pour lire le livre à votre rythme, annoter les passages clés et commencer votre propre chemin de leadership.',
          cta: 'Commander sur WhatsApp',
          quantity: 1,
          customerType: 'individual',
          preferredMode: 'delivery',
        },
        {
          id: 'duo',
          eyebrow: 'Transmission',
          title: 'Pack duo',
          body: 'Un exemplaire pour vous, un exemplaire à offrir à une personne en croissance.',
          cta: 'Commander sur WhatsApp',
          quantity: 2,
          customerType: 'individual',
          preferredMode: 'delivery',
          groupRequest: true,
        },
        {
          id: 'team',
          eyebrow: 'Lecture collective',
          title: 'Pack équipe',
          body: 'Pour managers, groupes, associations, clubs de lecture ou communautés qui veulent réfléchir ensemble.',
          cta: 'Commander sur WhatsApp',
          quantity: 10,
          customerType: 'organization',
          preferredMode: 'delivery',
          groupRequest: true,
        },
        {
          id: 'enterprise',
          eyebrow: 'Organisation',
          title: 'Entreprise / institution',
          body: 'Pour RH, écoles, programmes jeunes talents, institutions, communautés et organisations.',
          cta: 'Commander sur WhatsApp',
          quantity: 25,
          customerType: 'enterprise',
          preferredMode: 'delivery',
          groupRequest: true,
          enterpriseRequest: true,
        },
        {
          id: 'special',
          eyebrow: 'Sur mesure',
          title: 'Commande spéciale',
          body: 'Pour volumes plus importants, exemplaires dédicacés, intervention de l’auteur ou format d’accompagnement.',
          cta: 'Contacter sur WhatsApp',
          quantity: 50,
          customerType: 'organization',
          preferredMode: 'delivery',
          groupRequest: true,
          enterpriseRequest: true,
        },
      ],
      amazon: {
        title: 'Acheter via Amazon si nécessaire',
        body: 'À utiliser lorsque ce canal est plus simple selon votre pays, vos habitudes d’achat ou les options de livraison disponibles.',
        cta: 'Acheter sur Amazon',
      },
    },
    contact: {
      eyebrow: 'Commande & suivi',
      title: 'Formulaire de commande',
      intro: 'Remplissez ce formulaire pour une commande individuelle, une demande groupée ou une proposition entreprise / institution. L’équipe vous contactera pour confirmer la disponibilité, le paiement et la livraison.',
      fields: {
        fullName: 'Nom et prénom',
        email: 'Email',
        whatsapp: 'Téléphone WhatsApp',
        location: 'Ville / pays',
        orderType: 'Type de commande',
        quantity: 'Nombre d’exemplaires souhaités',
        preferredMode: 'Mode préféré',
        customerType: 'Vous êtes',
        message: 'Message ou besoin spécifique',
        ambassadorCode: 'Code ambassadeur / personne qui vous a recommandé le livre',
      },
      placeholders: {
        fullName: 'Votre nom complet',
        whatsapp: '+225…',
        location: 'Abidjan, Côte d’Ivoire',
        message: 'Précisez le contexte, la date souhaitée, le public concerné ou toute contrainte utile.',
        ambassadorCode: 'Code ou nom, si applicable',
      },
      orderTypes: [
        { value: 'single', label: '1 exemplaire' },
        { value: 'duo', label: 'Pack duo' },
        { value: 'team', label: 'Pack équipe / groupe' },
        { value: 'enterprise', label: 'Pack entreprise / institution' },
        { value: 'special', label: 'Commande spéciale / intervention' },
        { value: 'amazon', label: 'Achat via Amazon' },
      ],
      preferredModes: [
        { value: 'delivery', label: 'Livraison' },
        { value: 'pickup', label: 'Retrait' },
        { value: 'amazon', label: 'Amazon' },
        { value: 'other', label: 'Autre' },
      ],
      customerTypes: [
        { value: 'individual', label: 'Particulier' },
        { value: 'enterprise', label: 'Entreprise' },
        { value: 'school', label: 'École / université' },
        { value: 'institution', label: 'Institution' },
        { value: 'association', label: 'Association' },
        { value: 'organization', label: 'Organisation / communauté' },
        { value: 'other', label: 'Autre' },
      ],
      submit: 'Envoyer ma demande',
      submitting: 'Envoi…',
      success: 'Merci. Votre demande a bien été envoyée. Notre équipe vous contactera pour confirmer les prochaines étapes.',
      emailFallback: 'ou nous écrire directement',
      privacy: 'Vos informations servent uniquement au suivi de votre demande liée au livre. Elles ne seront pas vendues ni partagées.',
      errors: {
        name: 'Merci d’indiquer votre nom et prénom.',
        email: 'Merci d’indiquer un email valide.',
        whatsapp: 'Merci d’indiquer un numéro WhatsApp valide.',
        location: 'Merci d’indiquer votre ville et votre pays.',
        config: 'Service indisponible pour le moment. Merci de nous écrire directement par email.',
        submit: 'Impossible d’envoyer votre demande. Réessayez ou écrivez-nous à contact@zonzerigueleadership.com.',
        network: 'Connexion interrompue. Merci de réessayer.',
      },
    },
    beyond: {
      eyebrow: 'Écosystème',
      title: 'AU-DELÀ DU LIVRE',
      lead: 'Le livre peut devenir un point de départ pour une expérience collective : masterclass, atelier, conférence, parcours de lecture guidée ou intervention adaptée à votre organisation.',
      sections: [
        {
          id: 'masterclass',
          eyebrow: 'Section 1',
          title: 'Masterclass autour du livre',
          body: 'Une session structurée pour approfondir les thèmes du livre : conscience de soi, agencité, vision, discipline intérieure, caractère, communication et impact.',
          cta: {
            type: 'keynote',
            accent: 'blue',
            label: 'Intervention',
            button: 'Demander une intervention',
            description: 'Public, objectifs, format et période souhaitée.',
          },
        },
        {
          id: 'workshops',
          eyebrow: 'Section 2',
          title: 'Ateliers pour équipes',
          body: 'Des ateliers pour aider une équipe à travailler la posture, la communication, la responsabilité, la décision et l’alignement entre vision et action.',
          cta: {
            type: 'keynote',
            accent: 'emerald',
            label: 'Format équipe',
            button: 'Discuter d’un format pour mon organisation',
            description: 'Nous vous aidons à cadrer le format le plus utile.',
          },
        },
        {
          id: 'enterprise',
          eyebrow: 'Section 3',
          title: 'Interventions en entreprise',
          body: 'Conférences, séminaires ou rencontres de leadership pour dirigeants, managers, jeunes talents, RH, associations professionnelles et communautés.',
          cta: {
            type: 'keynote',
            accent: 'purple',
            label: 'Entreprise',
            button: 'Demander une intervention',
            description: 'Organisation, contexte, public et objectifs.',
          },
        },
        {
          id: 'guided-reading',
          eyebrow: 'Section 4',
          title: 'Parcours de lecture guidée',
          body: 'Un dispositif pour lire le livre en groupe, chapitre après chapitre, avec questions, échanges, exercices et temps d’intégration.',
          cta: {
            type: 'keynote',
            accent: 'orange',
            label: 'Lecture collective',
            button: 'Demander un parcours de lecture',
            description: 'Partagez le nombre de participants, le contexte et la période souhaitée.',
          },
        },
        {
          id: 'conferences',
          eyebrow: 'Section 5',
          title: 'Conférences',
          body: 'Des conférences pour ouvrir une conversation forte sur le leadership transformationnel, la responsabilité, le service, le caractère et l’impact durable.',
          cta: {
            type: 'keynote',
            accent: 'rose',
            label: 'Conférence',
            button: 'Demander une intervention',
            description: 'Format présentiel, hybride ou en ligne.',
          },
        },
        {
          id: 'zli',
          eyebrow: 'Section 6',
          title: 'Lien avec La Fabrique des Leaders / ZLI',
          body: 'La Fabrique du Leader s’inscrit dans l’écosystème de Zonzerigue Leadership International (ZLI), qui prolonge les principes du livre à travers des programmes, expériences et formats d’accompagnement.',
          cta: {
            type: 'link',
            accent: 'emerald',
            label: 'Écosystème',
            button: 'Découvrir ZLI',
            description: 'Ouvre le site ZLI dans un nouvel onglet.',
            href: 'https://zonzerigueleadership.com/',
            external: true,
          },
        },
      ],
      closing: {
        title: 'Au-delà du livre, le leadership devient une pratique.',
        body: 'Chaque format peut être adapté à votre public, votre maturité, votre contexte et vos objectifs de transformation.',
      },
    },
    why: {
      title: 'Pourquoi ce livre ?',
      lead: 'Et si c’était maintenant que votre leadership prenait une **nouvelle direction** ?',
      body: "La Fabrique du Leader n’est pas un simple manuel de management. C’est une **fabrique intérieure** : un chemin pour **aligner** votre **posture**, vos **compétences** et votre **caractère**.",
      bullets: [
        '🔍 **Clarté intérieure** – Développez votre conscience de soi.',
        '⚖️ **Alignement** – Transformez vos valeurs en décisions cohérentes.',
        '🌍 **Impact** – Inspirez et influencez votre environnement.',
      ],
      sales: 'Ce livre est conçu pour être lu seul, offert à une personne en croissance, ou utilisé comme support de réflexion collective dans une équipe, une organisation ou une communauté.',
      cta: 'Je veux forger mon leadership',
    },
    author: {
      title: 'Rencontrez DS Zonzerigue',
      body: [
        'Fondateur de Zonzerigue Leadership International (ZLI), formateur, conférencier et auteur engagé, DS Zonzerigue accompagne celles et ceux qui veulent allier **exigence intérieure**, **impact durable** et **alignement profond** dans leur vie personnelle, communautaire et professionnelle. Il a choisi de quitter les sentiers tracés pour répondre à une question essentielle :',
        '*Quel type de leader suis-je en train de devenir ? Et suis‑je encore fidèle à ce qui m’anime ?*',
        'Ce livre est le fruit d’un cheminement personnel, mais surtout d’une conviction :',
        '**Le leadership transformationnel commence par soi - ou il ne transforme rien.**',
        'À travers ce livre, il transmet une vision du leadership ancrée, humaine, structurée. Pas une recette. Un chemin.',
        '*Celui de celles et ceux qui osent se forger de l’intérieur pour mieux éclairer le monde autour d’eux.*',
      ],
    },
    about: {
      title: 'À propos du livre',
      body: [
        'La Fabrique du Leader est une invitation à la transformation intérieure. Ce livre vous guide pour devenir un leader lucide, aligné et capable de générer un impact durable.',
        'Trois piliers structurent ce chemin :',
      ],
      pillars: [
        '**Mindset transformationnel** – Développer la **conscience de soi** et dépasser ses conditionnements.',
        '**Compétences clés** – Apprendre à communiquer, décider et inspirer avec clarté et influence.',
        '**Fondations du caractère** – Bâtir une **force intérieure** et une cohérence profonde, sources de confiance et de stabilité.',
      ],
      closing: 'Un livre à la fois introspectif et pratique : réflexions profondes, récits inspirants, exercices concrets.',
      cta: 'Commander votre exemplaire',
    },
    learn: {
      title: 'Ce que vous allez apprendre',
      bullets: [
        'Dépasser vos conditionnements intérieurs.',
        'Clarifier et incarner votre vision.',
        'Développer des habitudes solides et durables.',
        'Communiquer pour inspirer et transformer.',
        'Forger un caractère aligné avec vos valeurs profondes.',
      ],
    },
    preface: {
      title: 'Préface',
      quote:
        "[Ajoutez ici le témoignage de l’auteur de la préface.]",
      author: {
        name: "[Nom de l’auteur de la préface]",
        role: '',
        photo: '', // Placez une image dans `public/` et indiquez le chemin, ex: '/preface.jpg'
      },
    },
    testimonials: {
      title: 'Ce que les premiers lecteurs en disent',
      intro:
        "Ces témoignages reflètent la diversité des voix qui ont lu ce livre avant sa publication officielle : dirigeants, professeurs, cadres, coachs, entrepreneurs, employés. Chacun parle depuis son expérience propre, avec son regard et sa sensibilité. Ensemble, ils rappellent que le leadership dépasse les titres et s’ancre avant tout dans l’intériorité.",
      quotes: [
        {
          name: 'Jean-Marc Mercy - Mercy Consulting Group, Coach exécutif',
          text:
            'La Fabrique du Leader est un miroir puissant qui révèle notre véritable identité et nous guide vers un leadership authentique, aligné et porteur de sens.',
        },
        {
          name: 'Karim Coulibaly - DGA, PETROCI (Abidjan)',
          text:
            'D. Zonzerigue éclaire un angle mort du leadership contemporain : la dimension intérieure. Ce livre rappelle avec force que le vrai pouvoir de transformation commence d’abord en soi. Une réflexion incontournable pour tout dirigeant.',
        },
        {
          name: 'Pr. Bakayoko Ismaila - Université de Cocody (Abidjan)',
          text:
            'Ce livre est d’une clarté exigeante et offre un véritable enseignement sur le leadership. Chaque chapitre propose des leviers concrets pour le changement d’attitude… En le lisant, j’ai eu le sentiment qu’il s’adressait directement à moi. Chapeau !',
        },
        {
          name: 'Siaka Soro - Employé',
          text:
            'Lire La Fabrique du Leader a été pour moi une révélation. On y découvre que le leadership n’est pas réservé aux cadres supérieurs ou aux dirigeants, mais qu’il commence dans la manière dont chacun se connaît et agit au quotidien. Ce livre m’a permis de valoriser mes forces, de comprendre mes limites et de voir que même à mon niveau, je peux inspirer, influencer et contribuer positivement autour de moi.',
        },
        {
          name: 'Plexie Koné-Mayne - Responsable Task Force Recrutement, Caisse des Dépôts et Consignations (Paris)',
          text:
            'La Fabrique du Leader vient percuter en nous une réalité souvent inconsciente : être leader ne s’improvise pas, ne se décrète pas. Cela se construit, pas à pas, en capitalisant sur nos expériences, nos forces, nos fragilités. Le vrai leadership commence toujours par la rencontre avec soi-même. Ce livre clair et inspirant montre un leadership profondément humain, qui trouve sa place au travail, dans la vie personnelle et dans la société.',
        },
        {
          name: 'Dr Kouadio Antoine - Université de Cocody (Abidjan)',
          text:
            'Ce n’est pas d’un énième livre sur le leadership technique, mais d’une exploration intérieure - rigoureusement maintenue tout au long des trois parties (Mindset, Compétences, Caractère). Ce livre est particulièrement touchant par son approche tournée vers l’intériorité et l’authenticité du leader. L’idée que le leadership n’est pas un rôle à jouer mais une façon d’exister est une perspective rafraîchissante et profonde.',
        },
        {
          name: 'Awa Diomandé - Abidjan',
          text:
            'La Fabrique du Leader déshabille. Elle met le lecteur face à des aspects de lui-même qu’il préfère souvent ignorer. C’est une lecture qui dérange, mais qui libère.',
        },
        {
          name: 'Nader Nahle - Abidjan',
          text:
            'Chaque passage m’interpelle fortement : la profondeur et l’authenticité du propos changent vraiment de ce qu’on lit habituellement sur le leadership. C’est un livre qui ne donne pas seulement des clés, mais qui pousse à une véritable introspection.',
        },
      ],
      outro: [
        "Autant de voix qui confirment une même évidence : ce livre est une invitation intérieure vers le leadership authentique.",
        "Et vous, êtes-vous prêt à entrer dans La Fabrique du Leader ?",
      ],
    },
    faq: {
      title: 'Questions fréquentes',
      items: [
        { q: 'Comment commander le livre ?', a: 'Choisissez l’offre qui vous convient puis cliquez sur Commander sur WhatsApp. Une conversation avec La Fabrique du Leader s’ouvrira avec votre offre et la quantité déjà renseignées. Envoyez le message pour recevoir le numéro Wave et finaliser le paiement.' },
        { q: 'Puis-je commander hors Amazon ?', a: 'Oui. Amazon reste une option disponible, notamment pour certains pays ou pour les personnes qui préfèrent ce canal. Mais vous pouvez également commander directement auprès de notre équipe, notamment pour les exemplaires dédicacés, les commandes groupées, les ventes locales, les organisations, les écoles ou les institutions.' },
        { q: 'Puis-je commander plusieurs exemplaires ?', a: 'Oui. Choisissez le pack duo, équipe, entreprise ou commande spéciale. WhatsApp s’ouvrira avec l’offre et la quantité correspondantes afin de poursuivre directement avec notre équipe.' },
        { q: 'Proposez-vous des packs pour équipes ou entreprises ?', a: 'Oui. Des packs peuvent être proposés pour les équipes, entreprises, institutions, écoles, associations, communautés ou groupes de lecture. Selon le besoin, le pack peut inclure simplement les livres, ou être complété par une masterclass, une intervention de l’auteur, un atelier ou un parcours de lecture guidée autour des thèmes du livre.' },
        { q: 'Peut-on offrir le livre ?', a: 'Oui. La Fabrique du Leader se prête particulièrement bien à l’idée de transmission. Vous pouvez l’offrir à un jeune professionnel, un manager, un entrepreneur, un collaborateur, un étudiant, un responsable d’équipe ou toute personne engagée dans un chemin de croissance personnelle et professionnelle.' },
        { q: 'Le livre est-il disponible en version papier et numérique ?', a: 'Le livre est prévu en version papier et en version numérique. La disponibilité exacte peut varier selon le pays, le canal de commande et la période. La version papier est recommandée pour celles et ceux qui souhaitent annoter, relire et utiliser le livre comme support de réflexion personnelle ou collective.' },
        { q: 'Quels sont les moyens de paiement disponibles ?', a: 'Pour une commande directe, le QR code de paiement Wave vous sera transmis dans la conversation WhatsApp. Amazon reste également disponible lorsque ce canal est plus adapté à votre pays ou à vos besoins de livraison.' },
        { q: 'Où livrez-vous ?', a: 'La livraison dépend du pays, de la ville et du stock disponible. Des options de livraison locale, de retrait ou d’expédition peuvent être proposées selon les cas. Pour les commandes internationales, Amazon ou d’autres solutions d’expédition peuvent être recommandés lorsque c’est plus simple ou plus fiable.' },
        { q: 'Peut-on inviter l’auteur pour une conférence, masterclass ou atelier ?', a: 'Oui. L’auteur peut être invité pour une conférence, une masterclass, un atelier ou une rencontre autour des thèmes du livre : leadership transformationnel, conscience de soi, agencité, vision, discipline intérieure, communication, caractère et impact. Les formats peuvent être adaptés aux entreprises, écoles, institutions, associations, communautés ou groupes de dirigeants.' },
        { q: 'Existe-t-il un extrait gratuit ?', a: 'Oui. Un extrait gratuit du livre est disponible. Il vous permet de découvrir le style, l’esprit et les premiers thèmes de La Fabrique du Leader avant de commander l’ouvrage complet. Vous pouvez le télécharger directement depuis cette page.' },
        { q: 'Le livre s’adresse-t-il uniquement aux managers ?', a: 'Non. Le livre ne s’adresse pas uniquement aux managers. Il parle à toute personne qui veut grandir en leadership, en conscience, en responsabilité et en impact. Il peut être utile aux jeunes professionnels, entrepreneurs, dirigeants, responsables d’équipes, étudiants, formateurs, responsables associatifs, communautés et organisations. Le point de départ du livre est simple : avant de diriger les autres, il faut apprendre à se diriger soi-même.' },
      ],
    },
    finalCta: {
      title: 'Le monde a besoin de leaders solides. Et si vous étiez l’un d’eux ?',
      sub: 'Commandez La Fabrique du Leader, équipez une communauté de lecture ou recevez l’extrait pour découvrir l’esprit du livre.',
      ctas: { preorder: 'Commander le livre', group: 'Demander une offre groupée', excerpt: 'Télécharger un extrait gratuit' },
    },
    footer: {
      contact: 'Contact',
      follow: 'Suivez-nous',
      email: 'contact@zonzerigueleadership.com',
      byline: 'Un programme de Zonzerigue Leadership International (ZLI)',
      socials: [
        { kind: 'linkedin', label: 'LinkedIn', url: 'https://www.linkedin.com/company/la-fabrique-du-leader' },
        // { kind: 'x', label: 'X', url: '#' },
        // { kind: 'instagram', label: 'Instagram', url: '#' },
        // { kind: 'youtube', label: 'YouTube', url: '#' },
        // { kind: 'facebook', label: 'Facebook', url: '#' },
        // { kind: 'tiktok', label: 'TikTok', url: '#' },
      ],
    },
  },
  en: {
    nav: { preorder: 'Order', excerpt: 'Download excerpt', beyond: 'Beyond the Book' },
    hero: {
      brand: "The Leader’s Inner Forge",
      title: 'Forge a lucid, grounded, and deeply human leadership.',
      sub: 'A transformational guide to becoming a strong, aligned, and visionary leader.',
      ctas: { preorder: 'Order the book', excerpt: 'Download a free excerpt' },
    },
    audience: {
      title: 'Who is this book for?',
      items: [
        { title: 'Young professionals', body: 'For clarifying direction, building inner discipline, and laying strong leadership foundations.' },
        { title: 'Managers', body: 'For knowing yourself better, communicating, delegating, deciding, and strengthening exemplary posture.' },
        { title: 'Executives', body: 'For aligning vision, decisions, and action with lucidity, character, and inner coherence.' },
        { title: 'Entrepreneurs', body: 'For building with vision, endurance, responsibility, and clarity in uncertain environments.' },
        { title: 'Team leaders', body: 'For guiding, mobilizing, and orienting others with more conscious and accurate influence.' },
        { title: 'HR / organizations', body: 'For developing a more conscious, responsible leadership culture that supports durable performance.' },
        { title: 'Schools and universities', body: 'For helping students and young talents build vision, agency, discipline, and responsibility.' },
        { title: 'Associations and groups', body: 'For opening collective conversations on character, service, influence, and personal transformation.' },
      ],
    },
    giftGroup: {
      title: 'Offer it or read it as a group',
      body: 'The Leader’s Inner Forge naturally lends itself to transmission. Offer it to a young leader, colleague, manager, entrepreneur, or someone on a growth path. It can also become the basis for group reading, a team discussion, a masterclass, or a workshop.',
      noteLabel: 'Collective use',
      note: 'For a team, school, community, or reading group, share the quantity and context so we can guide you toward the right format.',
      ctas: {
        bulk: 'Order several copies',
        team: 'Request an offer for my team',
      },
    },
    order: {
      eyebrow: 'Direct order',
      title: 'Order the book',
      intro: 'Choose your package and continue on WhatsApp. Your order message will be prepared automatically, and you will receive the Wave number to complete payment.',
      options: [
        {
          id: 'single',
          eyebrow: 'Personal reading',
          title: '1 copy',
          body: 'Read at your pace, annotate key passages, and begin your own leadership path.',
          cta: 'Order on WhatsApp',
          quantity: 1,
          customerType: 'individual',
          preferredMode: 'delivery',
        },
        {
          id: 'duo',
          eyebrow: 'Transmission',
          title: 'Duo pack',
          body: 'One copy for you, one copy to offer to someone who is growing.',
          cta: 'Order on WhatsApp',
          quantity: 2,
          customerType: 'individual',
          preferredMode: 'delivery',
          groupRequest: true,
        },
        {
          id: 'team',
          eyebrow: 'Group reading',
          title: 'Team pack',
          body: 'For managers, groups, associations, reading clubs, or communities that want to reflect together.',
          cta: 'Order on WhatsApp',
          quantity: 10,
          customerType: 'organization',
          preferredMode: 'delivery',
          groupRequest: true,
        },
        {
          id: 'enterprise',
          eyebrow: 'Organization',
          title: 'Company / institution',
          body: 'For HR, schools, young talent programs, institutions, communities, and organizations.',
          cta: 'Order on WhatsApp',
          quantity: 25,
          customerType: 'enterprise',
          preferredMode: 'delivery',
          groupRequest: true,
          enterpriseRequest: true,
        },
        {
          id: 'special',
          eyebrow: 'Custom',
          title: 'Special order',
          body: 'For larger volumes, signed copies, author interventions, or a guided support format.',
          cta: 'Contact us on WhatsApp',
          quantity: 50,
          customerType: 'organization',
          preferredMode: 'delivery',
          groupRequest: true,
          enterpriseRequest: true,
        },
      ],
      amazon: {
        title: 'Buy via Amazon if needed',
        body: 'Use this option when it is simpler based on your country, purchase habits, or available delivery options.',
        cta: 'Buy on Amazon',
      },
    },
    contact: {
      eyebrow: 'Order & follow-up',
      title: 'Order form',
      intro: 'Use this form for an individual order, group request, or company / institutional proposal. Our team will contact you to confirm availability, payment, and delivery.',
      fields: {
        fullName: 'Full name',
        email: 'Email',
        whatsapp: 'WhatsApp phone',
        location: 'City / country',
        orderType: 'Order type',
        quantity: 'Desired number of copies',
        preferredMode: 'Preferred mode',
        customerType: 'You are',
        message: 'Message or specific need',
        ambassadorCode: 'Ambassador code / person who recommended the book',
      },
      placeholders: {
        fullName: 'Your full name',
        whatsapp: '+1…',
        location: 'New York, United States',
        message: 'Share the context, desired timing, audience, or any useful constraint.',
        ambassadorCode: 'Code or name, if applicable',
      },
      orderTypes: [
        { value: 'single', label: '1 copy' },
        { value: 'duo', label: 'Duo pack' },
        { value: 'team', label: 'Team / group pack' },
        { value: 'enterprise', label: 'Company / institution pack' },
        { value: 'special', label: 'Special order / intervention' },
        { value: 'amazon', label: 'Amazon purchase' },
      ],
      preferredModes: [
        { value: 'delivery', label: 'Delivery' },
        { value: 'pickup', label: 'Pickup' },
        { value: 'amazon', label: 'Amazon' },
        { value: 'other', label: 'Other' },
      ],
      customerTypes: [
        { value: 'individual', label: 'Individual' },
        { value: 'enterprise', label: 'Company' },
        { value: 'school', label: 'School / university' },
        { value: 'institution', label: 'Institution' },
        { value: 'association', label: 'Association' },
        { value: 'organization', label: 'Organization / community' },
        { value: 'other', label: 'Other' },
      ],
      submit: 'Send my request',
      submitting: 'Sending…',
      success: 'Thank you. Your request has been sent. Our team will contact you to confirm next steps.',
      emailFallback: 'or write to us directly',
      privacy: 'Your information is used only to follow up on your book-related request. It will not be sold or shared.',
      errors: {
        name: 'Please enter your full name.',
        email: 'Please enter a valid email.',
        whatsapp: 'Please enter a valid WhatsApp number.',
        location: 'Please enter your city and country.',
        config: 'Service unavailable at the moment. Please email us directly.',
        submit: 'Unable to send your request. Please try again or email contact@zonzerigueleadership.com.',
        network: 'Network error. Please try again.',
      },
    },
    beyond: {
      eyebrow: 'Ecosystem',
      title: 'BEYOND THE BOOK',
      lead: 'The book can become the starting point for a collective experience: masterclass, workshop, keynote, guided reading journey, or intervention tailored to your organization.',
      sections: [
        {
          id: 'masterclass',
          eyebrow: 'Section 1',
          title: 'Masterclass around the book',
          body: 'A structured session to go deeper into the book’s themes: self-awareness, agency, vision, inner discipline, character, communication, and impact.',
          cta: {
            type: 'keynote',
            accent: 'blue',
            label: 'Intervention',
            button: 'Request an intervention',
            description: 'Audience, goals, format, and desired timing.',
          },
        },
        {
          id: 'workshops',
          eyebrow: 'Section 2',
          title: 'Workshops for teams',
          body: 'Workshops to help a team work on posture, communication, responsibility, decision-making, and alignment between vision and action.',
          cta: {
            type: 'keynote',
            accent: 'emerald',
            label: 'Team format',
            button: 'Discuss a format for my organization',
            description: 'We help you define the most useful format.',
          },
        },
        {
          id: 'enterprise',
          eyebrow: 'Section 3',
          title: 'Corporate interventions',
          body: 'Keynotes, seminars, or leadership sessions for executives, managers, young talents, HR teams, professional associations, and communities.',
          cta: {
            type: 'keynote',
            accent: 'purple',
            label: 'Company',
            button: 'Request an intervention',
            description: 'Organization, context, audience, and goals.',
          },
        },
        {
          id: 'guided-reading',
          eyebrow: 'Section 4',
          title: 'Guided reading journey',
          body: 'A group reading format, chapter by chapter, with questions, discussion, exercises, and integration time.',
          cta: {
            type: 'keynote',
            accent: 'orange',
            label: 'Collective reading',
            button: 'Request a reading journey',
            description: 'Share the number of participants, context, and desired timing.',
          },
        },
        {
          id: 'conferences',
          eyebrow: 'Section 5',
          title: 'Conferences',
          body: 'Talks that open a strong conversation on transformational leadership, responsibility, service, character, and lasting impact.',
          cta: {
            type: 'keynote',
            accent: 'rose',
            label: 'Conference',
            button: 'Request an intervention',
            description: 'In-person, hybrid, or online format.',
          },
        },
        {
          id: 'zli',
          eyebrow: 'Section 6',
          title: 'Connection with La Fabrique des Leaders / ZLI',
          body: 'The Leader’s Inner Forge belongs to the Zonzerigue Leadership International (ZLI) ecosystem, which extends the book’s principles through programs, experiences, and support formats.',
          cta: {
            type: 'link',
            accent: 'emerald',
            label: 'Ecosystem',
            button: 'Explore ZLI',
            description: 'Opens zonzerigueleadership.com in a new tab.',
            href: 'https://zonzerigueleadership.com/',
            external: true,
          },
        },
      ],
      closing: {
        title: 'Beyond the book, leadership becomes a practice.',
        body: 'Each format can be adapted to your audience, maturity, context, and transformation goals.',
      },
    },
    why: {
      title: 'Why this book?',
      lead: 'What if now was the time for your leadership to take a **new direction**?',
      body: 'The Leader’s Inner Forge is not just another management manual. It is an **inner workshop**: a path to **align** your **mindset**, **skills**, and **character**.',
      bullets: [
        '🔍 **Clarity** – Develop deeper self-awareness.',
        '⚖️ **Alignment** – Turn your values into coherent decisions.',
        '🌍 **Impact** – Inspire and positively influence your environment.',
      ],
      sales: 'This book is designed to be read alone, offered to someone who is growing, or used as a collective reflection support in a team, organization, or community.',
      cta: 'I want to forge my leadership',
    },
    author: {
      title: 'Meet DS Zonzerigue',
      body: [
        'Founder of Zonzerigue Leadership International (ZLI), trainer, speaker, and committed author, DS Zonzerigue supports those who want to combine **inner rigor**, **lasting impact**, and **deep alignment** in their personal, community, and professional life. He chose to leave the beaten path to answer an essential question:',
        '*What kind of leader am I becoming? And am I still faithful to what drives me?*',
        'This book is the result of a personal journey, but above all of a conviction:',
        '**Transformational leadership begins within - or it does not transform anything.**',
        'Through this book, he shares a grounded, human, and structured vision of leadership. Not a recipe. A path.',
        '*One for those who dare to forge themselves from within to better illuminate the world around them.*',
      ],
    },
    about: {
      title: 'About the book',
      body: [
        'The Leader’s Inner Forge is an invitation to inner transformation. This book is a guide to becoming a lucid, aligned leader capable of creating lasting impact.',
        'It is built around three fundamental pillars:',
      ],
      pillars: [
        '**Transformational mindset** – Developing **self-awareness** and transcending inner conditioning.',
        '**Core leadership skills** – Learning to communicate, decide, and inspire with clarity and influence.',
        '**Foundations of character** – Building **inner strength** and coherence as sources of trust and stability.',
      ],
      closing: 'A book that is both introspective and practical: deep insights, inspiring stories, and actionable exercises.',
      cta: 'Order your copy',
    },
    learn: {
      title: 'What you will learn',
      bullets: [
        'Overcome limiting mindsets and conditioning.',
        'Clarify and embody your vision.',
        'Build sustainable and powerful habits.',
        'Communicate to inspire and transform.',
        'Forge a character fully aligned with your deepest values.',
      ],
    },
    preface: {
      title: 'Preface',
      quote: '[Add the preface author’s testimonial here.]',
      author: { name: "[Preface author’s name]", role: '', photo: '' },
    },
    testimonials: {
      title: 'What early readers are saying',
      intro:
        'These testimonials reflect the diversity of voices who read this book before its official release: executives, professors, managers, coaches, entrepreneurs, and employees. Each speaks from their own experience, with their perspective and sensitivity. Together, they remind us that leadership goes beyond titles and is rooted first and foremost in inner life.',
      quotes: [
        {
          name: 'Jean-Marc Mercy - Mercy Consulting Group, Executive Coach',
          text:
            "The Leader’s Forge is a powerful mirror that reveals our true identity and guides us toward an authentic, aligned, and meaningful leadership.",
        },
        {
          name: 'Karim Coulibaly - Deputy CEO, PETROCI (Abidjan)',
          text:
            'D. Zonzerigue sheds light on a blind spot of contemporary leadership: the inner dimension. This book powerfully reminds us that true transformative power begins within. A must-read for every leader.',
        },
        {
          name: 'Prof. Bakayoko Ismaila - University of Cocody (Abidjan)',
          text:
            'This book is demanding in its clarity and offers a genuine education in leadership. Each chapter provides concrete levers for changing attitudes… As I read, I felt it was speaking directly to me. Bravo!',
        },
        {
          name: 'Siaka Soro - Employee',
          text:
            'Reading The Leader’s Forge was a revelation for me. You discover that leadership is not reserved for senior managers or executives, but begins in how each of us knows ourselves and acts daily. This book helped me value my strengths, understand my limits, and see that-even at my level-I can inspire, influence, and contribute positively around me.',
        },
        {
          name: 'Plexie Koné-Mayne - Head of Recruitment Task Force, Caisse des Dépôts et Consignations (Paris)',
          text:
            'The Leader’s Forge confronts us with a reality we often ignore: leadership is neither improvised nor decreed. It is built, step by step, by capitalizing on our experiences, strengths, and vulnerabilities. True leadership always begins with meeting oneself. Clear and inspiring, this book shows a deeply human leadership that finds its place at work, in personal life, and in society.',
        },
        {
          name: 'Dr. Kouadio Antoine - University of Cocody (Abidjan)',
          text:
            'This is not yet another book on technical leadership, but an inner exploration-rigorously sustained across the three parts (Mindset, Skills, Character). It is particularly moving in its focus on the leader’s inner life and authenticity. The idea that leadership is not a role to play but a way of being is refreshing and profound.',
        },
        {
          name: 'Awa Diomandé - Abidjan',
          text:
            'The Leader’s Forge lays the reader bare. It confronts you with aspects of yourself you would often rather ignore. It is a disquieting read-but a liberating one.',
        },
        {
          name: 'Nader Nahle - Abidjan',
          text:
            'Every passage spoke to me powerfully. The depth and authenticity truly stand apart from most leadership books. It doesn’t just hand you a set of keys-it pushes you into genuine introspection.',
        },
      ],
      outro: [
        "So many voices confirm the same truth: this book is an inner invitation to authentic leadership.",
        "And you - are you ready to step into The Leader’s Forge?",
      ],
    },
    faq: {
      title: 'Frequently asked questions',
      items: [
        { q: 'How can I order the book?', a: 'Choose the package that suits you, then click Order on WhatsApp. A conversation with La Fabrique du Leader will open with your package and quantity already filled in. Send the message to receive the Wave number and complete payment.' },
        { q: 'Can I order outside Amazon?', a: 'Yes. Amazon remains available for some countries or for people who prefer that channel, but you can also order directly from our team, especially for signed copies, group orders, local sales, organizations, schools, and institutions.' },
        { q: 'Can I order several copies?', a: 'Yes. Choose the duo, team, company, or special-order package. WhatsApp will open with the matching package and quantity so you can continue directly with our team.' },
        { q: 'Do you offer team or company packs?', a: 'Yes. Packs can be created for teams, companies, institutions, schools, associations, communities, or reading groups. Depending on the need, the pack can include books only or be combined with a masterclass, author intervention, workshop, or guided reading journey.' },
        { q: 'Can I offer the book as a gift?', a: 'Yes. The book is well suited to transmission. You can offer it to a young professional, manager, entrepreneur, colleague, student, team leader, or anyone committed to personal and professional growth.' },
        { q: 'Is the book available in print and digital?', a: 'The book is planned in print and digital formats. Exact availability may vary by country, order channel, and timing. The print version is recommended for readers who want to annotate, reread, and use it as a personal or collective reflection support.' },
        { q: 'What payment methods are available?', a: 'For direct orders, the Wave payment QR code will be sent to you in the WhatsApp conversation. Amazon also remains available when it is better suited to your country or delivery needs.' },
        { q: 'Where do you deliver?', a: 'Delivery depends on the country, city, and available stock. Local delivery, pickup, or shipping may be proposed depending on the case. For international orders, Amazon or another shipping solution may be recommended when simpler or more reliable.' },
        { q: 'Can the author be invited for a conference, masterclass, or workshop?', a: 'Yes. The author can be invited for a conference, masterclass, workshop, or meeting around the book’s themes: transformational leadership, self-awareness, agency, vision, inner discipline, communication, character, and impact. Formats can be adapted to companies, schools, institutions, associations, communities, or executive groups.' },
        { q: 'Is there a free excerpt?', a: 'Yes. A free excerpt is available so you can discover the style, spirit, and first themes of the book before ordering the full work. You can download it directly from this page.' },
        { q: 'Is the book only for managers?', a: 'No. The book is not only for managers. It speaks to anyone who wants to grow in leadership, consciousness, responsibility, and impact. It can be useful for young professionals, entrepreneurs, executives, team leaders, students, trainers, association leaders, communities, and organizations. The starting point is simple: before leading others, you must learn to lead yourself.' },
      ],
    },
    finalCta: {
      title: 'The world needs strong leaders. What if you were one of them?',
      sub: 'Order The Leader’s Inner Forge, equip a reading community, or receive the excerpt to discover the spirit of the book.',
      ctas: { preorder: 'Order the book', group: 'Request a group offer', excerpt: 'Download a free excerpt' },
    },
    footer: {
      contact: 'Contact',
      follow: 'Follow us',
      email: 'contact@zonzerigueleadership.com',
      byline: 'A program by Zonzerigue Leadership International (ZLI)',
      socials: [
        { kind: 'linkedin', label: 'LinkedIn', url: 'https://www.linkedin.com/company/la-fabrique-du-leader' },
        // { kind: 'x', label: 'X', url: '#' },
        // { kind: 'instagram', label: 'Instagram', url: '#' },
        // { kind: 'youtube', label: 'YouTube', url: '#' },
        // { kind: 'facebook', label: 'Facebook', url: '#' },
        // { kind: 'tiktok', label: 'TikTok', url: '#' },
      ],
    },
  },
}
